version: '3.5'

services:
  web_app:
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - 2000:2000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis
      - psgrsql
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./db_data/redis:/data
    restart: always
  psgrsql:
    build:
      context: .
      dockerfile: Dockerfile_psql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db_data/psql:/var/lib/postgresql/data